# CSE x25 Final Project
TOP_MODULE += sine
SYNTH_SOURCES += $(TOP_MODULE).sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
SYNTH_SOURCES += ../../provided_modules/axis_i2s2.v
SYNTH_SOURCES += ../../provided_modules/inv.sv
SYNTH_SOURCES += ../../provided_modules/dff.sv
SYNTH_SOURCES += ../../provided_modules/shift.sv
SYNTH_SOURCES += ram_1r1w_sync.sv
#SYNTH_SOURCES += sine.sv
-include ../../simulation.mk
-include ../../fpga.mk
